flush ruleset
table inet filter {
    #Tráfico hacia la máquina
    chain input {
        type filter hook input priority 0; policy drop;
        # Permitir tráfico ya establecido
        ct state established,related accept
        # Permitir todo lo interno (Loopback)
        iif lo accept
        # Permitir SSH (Puerto 22)
        tcp dport 22 accept
        # Permitir ICMP (Ping)
        icmp type echo-request accept
    }
    chain forward {
        type filter hook forward priority 0; policy drop;
        # Permitir tráfico establecido (necesario para que respondan los contenedores)
        ct state established,related accept
        # PERMITIR HACIA AFUERA
        tcp dport { 80, 81, 443, 8008 } accept
        # PERMITIR TRÁFICO
        iifname "docker0" oifname "docker0" accept
        # Para que los contenedores se vean entre sí
        ip saddr 172.16.0.0/12 ip daddr 172.16.0.0/12 accept
    }
    chain output {
        type filter hook output priority 0; policy accept;
    }
}