[shared]
path = /etc/samba/shared
browseable = yes
#Let anon users
public = yes
#Let only anon users not registered
guest only = yes
#Let them work on this dir
writeable = yes
#Time until they get kicked out
deadtime = 5
#Let them finish until sync
strict sync = yes
sync allways = yes