name: Generación base de datos de comandos 

on:
  push:
    paths:
      - 'commands/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Conigurar python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ejecución de generador
        run: python .github/scripts/commands_db_gen.py

      - name: Commit y publicar
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: actualización base datos de comandos"
          file_pattern: '.github/db/commands.json'